version: '3.0'

services:
  front-proxy:
    container_name: front-proxy
    image: envoyproxy/envoy:latest
    volumes:
      - ./front-proxy/envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - 10000:10000
      - 9901:9901

  slack-proxy:
    container_name: slack-proxy
    image: nginx:alpine
    volumes:
      - ./slack-proxy/slack-proxy.conf:/etc/nginx/conf.d/slack-proxy.conf
    ports:
      - 80:80

  runner:
    container_name: runner
    build:
      context: ./runner
      dockerfile: ./Dockerfile
    volumes:
      - ./runner/app.rb:/app/app.rb
    depends_on: [front-proxy, slack-proxy]
